// <auto-generated />
using System;
using CiudadanosServicesCS.NombresPropios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CiudadanosServicesCS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CiudadanosServicesCS.NombresPropios.Models.NombrePropioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PkiNombrePropio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("FdFechaCreacion");

                    b.Property<string>("NombrePropio")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("FcNombrePropio");

                    b.Property<int>("UsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("FiUsuarioCreacion");

                    b.HasKey("Id");

                    b.ToTable("TB_NombresPropios", "Ciudadanos");
                });
#pragma warning restore 612, 618
        }
    }
}
